- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  setPreference: false
  icon: "ShaftMiner"
  startingGear: SalvageSpecialistGear
  departments:
  - Engineering
  supervisors: job-supervisors-hop-qm
  access:
  - Engineering
  - Maintenance
  - Salvage
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
